name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ChangeTimestamp # 修改为实际的解决方案所在目录

    - name: Use .NET Framework version 4.0
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        dotnet-version: '4.0'

    - name: Restore NuGet packages
      working-directory: ChangeTimestamp # 修改为实际的解决方案所在目录
      run: nuget restore ChangeTimestamp.sln

    - name: Build solution
      working-directory: ChangeTimestamp # 修改为实际的解决方案所在目录
      run: msbuild.exe ChangeTimestamp.sln /t:Build /p:Configuration=Release

    - name: Run tests
      working-directory: ChangeTimestamp/TestProject # 修改为实际的测试项目所在目录
      run: vstest.console.exe YourTestProject.dll /Logger:trx

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          ChangeTimestamp/bin/Release/*
          ChangeTimestamp/TestProject/TestResults/*.trx
