name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use .NET Framework version 4.0
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        dotnet-version: '4.0'

    - name: Restore NuGet packages
      run: nuget restore YourSolution.sln

    - name: Build solution
      run: msbuild.exe YourSolution.sln /t:Build /p:Configuration=Release

    - name: Run tests
      run: vstest.console.exe YourTestProject.dll /Logger:trx

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          YourSolution/bin/Release/*
          YourTestProject/TestResults/*.trx
